# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.1
maven_group = dev.djefrey
archives_name = colorwheel_patcher
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.0

# Build dependency mod versions
sodium_version = mc1.20.1-0.5.11
embeddium_version = 0.3.25+mc1.20.1
iris_version = 1.7.6+1.20.1
oculus_version = 1.20.1-1.7.0
euphoria_version = 1.6.4-r5.5.1
