# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.2.2
maven_group = dev.djefrey
archives_name = colorwheel_patcher
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.116.1+1.21.1
neoforge_version = 21.1.172

# Build dependency mod versions
sodium_version = 0.6.13
iris_version = 1.8.8
euphoria_version = 1.6.4-r5.5.1
